[project]
name = "chart-ticker"
version = "0.1.0"
description = "stock market with llm integration stuff"
readme = "README.txt"
requires-python = ">=3.13"
dependencies = [
    "kagglehub>=0.3.12",
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "tqdm>=4.67.1",
]
